name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, pdo, pdo_mysql, xml, bcmath
        coverage: none

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate app key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up testing database
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=testing" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=password" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "LOG_LEVEL=debug" >> .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Create empty frontend assets for testing
      run: |
        mkdir -p public/build/assets
        echo "/* Test CSS */" > public/build/assets/app.css
        echo "/* Test JS */" > public/build/assets/app.js
        echo '{"resources/css/app.css":{"file":"assets/app.css","isEntry":true},"resources/js/app.js":{"file":"assets/app.js","isEntry":true}}' > public/build/manifest.json

    - name: Run tests with verbose output
      run: php artisan test --verbose

    - name: Show Laravel logs on failure
      if: failure()
      run: |
        echo "=== Laravel Error Logs ==="
        cat storage/logs/laravel.log || echo "No Laravel log file found"
        echo "=== PHP Error Logs ==="
        php -l storage/logs/laravel.log || echo "No syntax errors in log file"
